# config/database.yml

default: &default
  adapter: postgresql # Change this to your preferred database adapter (e.g., mysql2 for MySQL)
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: db_admin
  password: dbadmin123
  host: localhost

development:
  <<: *default
  database: ror_recipe_app

test:
  <<: *default
  database: your_app_test

production:
  <<: *default
  database: your_app_production
  username: your_production_database_username
  password: your_production_database_password
  host: your_production_database_host
